### ISSUE TITLE
Installing fails (clock_gettime problem on Linux)

### ISSUE THREAD

**Issue by ghost** [copiousfreetime/hitimes#26]
Hi there. I'm trying to install `hitimes` on Debian Testing by

```
$  sudo gem install hitimes -v '1.2.2'
```

which gives me 

```
/usr/bin/ruby2.1 extconf.rb                                                                                                                                                
checking for clock_gettime() in -lrt... *** extconf.rb failed *** 
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may 
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/ruby2.1
    --with-rtlib
    --without-rtlib
/usr/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /usr/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
    from /usr/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
    from /usr/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
    from /usr/lib/ruby/2.1.0/mkmf.rb:973:in `block in have_library'
    from /usr/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
    from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /usr/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
    from /usr/lib/ruby/2.1.0/mkmf.rb:968:in `have_library'
    from extconf.rb:10:in `<main>'

extconf failed, exit code 1
```

I've read the other two related issues, but i'm not running BSD and already trying to install 1.2.2.
My environment:

```
$ ruby -e 'puts RUBY_DESCRIPTION'
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
$ gem -v
2.2.2
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.8.3-9' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.3 (Debian 4.8.3-9)
```

I'm not sure if the requested development tools are related to the `clock_gettime` problem. By the way, exactly what development tools are requested here? 
Thanks!

**Comment by NisreenJ** [comment]
Is there a Windows equivalent of this answer?

**Comment by copiousfreetime** [comment]
@NisreenJ you shouldn't need the ruby development kit to use hitimes on windows, hitimes for ships with a binary blob gem for windows that includes the already compiled code.

If you would paste the output of `gem install -V hitimes` into a new ticket we can investigate and figure out what is happening in your situation.
