### ISSUE TITLE
`require': cannot load such file -- hitimes/hitimes

### ISSUE THREAD

**Issue by AfonsoTsukamoto** [copiousfreetime/hitimes#33]
Hi!
While trying to use celluloid with ruby 2.1.5, I got the aforementioned error.
Then I removed all my requires from the configuration file and left hitimes alone. I got the same error.
The stack: 

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- hitimes/hitimes (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/afonsotsukamoto/.rvm/gems/ruby-2.1.5@dbwriter/gems/hitimes-1.2.2/lib/hitimes.rb:37:in `rescue in <top (required)>'
	from /Users/afonsotsukamoto/.rvm/gems/ruby-2.1.5@dbwriter/gems/hitimes-1.2.2/lib/hitimes.rb:32:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from ./updater.rb:2:in `<main>'
```

I'm using sidekiq, which uses celluloid, therefore, is using hitimes too, and that project runs smoothly. 
The only difference is the ruby version: 1.9.3.

Our file is simply a executable ruby script as follow:

```
#!/usr/bin/ruby

require 'hitimes'
```
In case you wonder, we also have a Gemfile with: 

```
source 'https://rubygems.org'
gem 'hitimes'
```

Any idea?

**Comment by AfonsoTsukamoto** [comment]
Nevermind, we had a stupid bug ( #!/usr/bin/ruby ) using system ruby.

**Comment by copiousfreetime** [comment]
No problem, glad to be a rubber-duck/cardboard programmer :smile_cat:

**Comment by AfonsoTsukamoto** [comment]
Ahahah! 
Next time you need some kind of 'bug relief' feel free to open an issue in any of my repositories! :smile:
