### ISSUE TITLE
Can't Seem to Install on Raspberry Pi

### ISSUE THREAD

**Issue by maddox** [copiousfreetime/hitimes#38]
I can't seem to install on the raspbery pi (Raspbian distro). I have `build-essential` and `ruby1.9.1-dev` installed, but it still can't seem to find `clock_gettime()`. 

I'm not sure if there's anything else I should be installing first to get it to build. Searches around the Internets proved futile.

Any insight into why this might be failing?

```
pi@new-host-8 ~/kart $ uname --all
Linux new-host-8 3.18.5-v7+ #225 SMP PREEMPT Fri Jan 30 18:53:55 GMT 2015 armv7l GNU/Linux
```

```
pi@new-host-8 ~/kart $ sudo gem install hitimes
Building native extensions.  This could take a while...
ERROR:  Error installing hitimes:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
checking for clock_gettime() in -lrt... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby1.9.1
	--with-rtlib
	--without-rtlib
/usr/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
	from /usr/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
	from /usr/lib/ruby/1.9.1/mkmf.rb:619:in `try_func'
	from /usr/lib/ruby/1.9.1/mkmf.rb:845:in `block in have_library'
	from /usr/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
	from /usr/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
	from /usr/lib/ruby/1.9.1/mkmf.rb:254:in `open'
	from /usr/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
	from /usr/lib/ruby/1.9.1/mkmf.rb:254:in `open'
	from /usr/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
	from /usr/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
	from /usr/lib/ruby/1.9.1/mkmf.rb:840:in `have_library'
	from extconf.rb:10:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/hitimes-1.2.2 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/hitimes-1.2.2/ext/hitimes/c/gem_make.out
```

**Comment by copiousfreetime** [comment]
Hitimes on a raspberry pi, that would be great! I have no clue at the moment, I'll see what I can dig up this weekend and let you know. My first thoughts will be in the direction of seeing if `clock_gettime()` is actually available as a system call on the raspberry pi.

**Comment by maddox** [comment]
Here's some info:

http://www.raspberry-projects.com/pi/programming-in-c/timing/clock_gettime-for-acurate-timing

**Comment by copiousfreetime** [comment]
Hey @maddox if this is something you're still interested in then I might dig into it again, otherwise probably not. Feel free to open this back up. Also, the ruby 2.1 `Process::clock_gettime` works on the rasberry pi then hitimes should work also, they both use the same underlying system call. Feel free to reopen.

**Comment by Stormcore** [comment]
Please, reopen, I have project that is based on Celluloid and it uses hitimes, is there any possibility to fix on raspberry pi?

**Comment by copiousfreetime** [comment]
Just an update on this, On a raspberry pi running raspbian all that was needed to make sure hitimes installed was `apt-get install build-essential`.

Basically we need the `librt.so` library and associated headers, along with the regular compiler tool chain. On raspbian this is taken care of by the libc6/libc6-dev packages.

```
pi@raspberrypi:~/hitimes $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 0010
Serial          : 00000000d7a2f407
```

And the install/test

```
pi@raspberrypi:~ $ sudo gem install hitimes
Fetching: hitimes-1.2.4.gem (100%)
Building native extensions.  This could take a while...
Successfully installed hitimes-1.2.4
1 gem installed

pi@raspberrypi:~ $ irb
irb(main):001:0> RUBY_VERSION
=> "2.4.1"
irb(main):002:0> require 'hitimes'
=> true
irb(main):003:0> Hitimes.measure { sleep 1 }
=> 1.000219979
irb(main):004:0>
```
