### ISSUE TITLE
Failed to install on Fedora 23 (at `checking for clock_gettime() in -lrt`)

### ISSUE THREAD

**Issue by shamiao** [copiousfreetime/hitimes#54]
- Linux localhost.localdomain 4.2.5-300.fc23.x86_64 #1 SMP Tue Oct 27 04:29:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
 - ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
 - gem 2.4.8

`gcc-g++`, `ruby-devel` and `glibc-devel` installed. 

`sudo gem install hitimes --verbose 2>&1` failed with following output:

```
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=hitimes
200 OK
/usr/local/share/gems/gems/hitimes-1.2.3/CONTRIBUTING.md
/usr/local/share/gems/gems/hitimes-1.2.3/HISTORY.md
/usr/local/share/gems/gems/hitimes-1.2.3/LICENSE
/usr/local/share/gems/gems/hitimes-1.2.3/Manifest.txt
/usr/local/share/gems/gems/hitimes-1.2.3/README.md
/usr/local/share/gems/gems/hitimes-1.2.3/Rakefile
/usr/local/share/gems/gems/hitimes-1.2.3/examples/benchmarks.rb
/usr/local/share/gems/gems/hitimes-1.2.3/examples/stats.rb
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/c/extconf.rb
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/c/hitimes.c
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_instant_clock_gettime.c
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_instant_osx.c
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_instant_windows.c
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_interval.c
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_interval.h
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_stats.c
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_stats.h
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/java/src/hitimes/Hitimes.java
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/java/src/hitimes/HitimesInterval.java
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/java/src/hitimes/HitimesService.java
/usr/local/share/gems/gems/hitimes-1.2.3/ext/hitimes/java/src/hitimes/HitimesStats.java
/usr/local/share/gems/gems/hitimes-1.2.3/lib/hitimes.rb
/usr/local/share/gems/gems/hitimes-1.2.3/lib/hitimes/metric.rb
/usr/local/share/gems/gems/hitimes-1.2.3/lib/hitimes/mutexed_stats.rb
/usr/local/share/gems/gems/hitimes-1.2.3/lib/hitimes/paths.rb
/usr/local/share/gems/gems/hitimes-1.2.3/lib/hitimes/stats.rb
/usr/local/share/gems/gems/hitimes-1.2.3/lib/hitimes/timed_metric.rb
/usr/local/share/gems/gems/hitimes-1.2.3/lib/hitimes/timed_value_metric.rb
/usr/local/share/gems/gems/hitimes-1.2.3/lib/hitimes/value_metric.rb
/usr/local/share/gems/gems/hitimes-1.2.3/lib/hitimes/version.rb
/usr/local/share/gems/gems/hitimes-1.2.3/spec/hitimes_spec.rb
/usr/local/share/gems/gems/hitimes-1.2.3/spec/interval_spec.rb
/usr/local/share/gems/gems/hitimes-1.2.3/spec/metric_spec.rb
/usr/local/share/gems/gems/hitimes-1.2.3/spec/mutex_stats_spec.rb
/usr/local/share/gems/gems/hitimes-1.2.3/spec/paths_spec.rb
/usr/local/share/gems/gems/hitimes-1.2.3/spec/spec_helper.rb
/usr/local/share/gems/gems/hitimes-1.2.3/spec/stats_spec.rb
/usr/local/share/gems/gems/hitimes-1.2.3/spec/timed_metric_spec.rb
/usr/local/share/gems/gems/hitimes-1.2.3/spec/timed_value_metric_spec.rb
/usr/local/share/gems/gems/hitimes-1.2.3/spec/value_metric_spec.rb
/usr/local/share/gems/gems/hitimes-1.2.3/spec/version_spec.rb
/usr/local/share/gems/gems/hitimes-1.2.3/tasks/default.rake
/usr/local/share/gems/gems/hitimes-1.2.3/tasks/extension.rake
/usr/local/share/gems/gems/hitimes-1.2.3/tasks/this.rb
Building native extensions.  This could take a while...
/usr/bin/ruby -r ./siteconf20151108-23376-1hce5xh.rb extconf.rb
checking for clock_gettime() in -lrt... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--with-rtlib
	--without-rtlib
/usr/share/ruby/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/share/ruby/mkmf.rb:541:in `try_link0'
	from /usr/share/ruby/mkmf.rb:556:in `try_link'
	from /usr/share/ruby/mkmf.rb:735:in `try_func'
	from /usr/share/ruby/mkmf.rb:966:in `block in have_library'
	from /usr/share/ruby/mkmf.rb:911:in `block in checking_for'
	from /usr/share/ruby/mkmf.rb:351:in `block (2 levels) in postpone'
	from /usr/share/ruby/mkmf.rb:321:in `open'
	from /usr/share/ruby/mkmf.rb:351:in `block in postpone'
	from /usr/share/ruby/mkmf.rb:321:in `open'
	from /usr/share/ruby/mkmf.rb:347:in `postpone'
	from /usr/share/ruby/mkmf.rb:910:in `checking_for'
	from /usr/share/ruby/mkmf.rb:961:in `have_library'
	from extconf.rb:10:in `<main>'
ERROR:  Error installing hitimes:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
extconf failed, exit code 1

Gem files will remain installed in /usr/local/share/gems/gems/hitimes-1.2.3 for inspection.
Results logged to /usr/local/lib64/gems/ruby/hitimes-1.2.3/gem_make.out
```

Content of log file `/usr/local/lib64/gems/ruby/hitimes-1.2.3/mkmf.log`:
```
"gcc -o conftest -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic -fPIC conftest.c  -L. -L/usr/lib64 -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic  -m64   -lruby  -lpthread -ldl -lcrypt -lm   -lc"
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

```

**Comment by shamiao** [comment]
`dnf install rpm-build` solved this issue. 

Never mind, case closed.

**Comment by MarcoWeiss** [comment]
Thank you shamiao for sharing that, it solved my problem too

**Comment by binary-data** [comment]
Thanks! Worked for me too

**Comment by hodwik** [comment]
Was having trouble with gem install pg on Fedora.

This answer worked for me also.

**Comment by jnjwatts** [comment]
My exact problem. My exact fix!! Cheers.

**Comment by alejandroandreu** [comment]
Thanks for sharing that ip, it worked too!

**Comment by mnuttall** [comment]
This fixed 'gem install travis' on Fedora for me - thank you.

**Comment by CathrineTeng** [comment]
So appreciate it! I have stuck on it !! It worked out!

**Comment by SUPERCILEX** [comment]
OMG thanks so much!!! I'v been trying to get `gem install travis` to work for like 3 hours!!! Thanks!

**Comment by luyaotsung** [comment]
thanks , it's also works for me
